In [1]:
# Start a SparkSession

import requests
import json
import sys
from pyspark.sql.functions import *
from pyspark.sql import functions as sf
from pyspark.sql.types import StructType, StructField, IntegerType, StringType,FloatType,DoubleType,ArrayType,TimestampType
from pyspark.sql import Row
import datetime as dt
from urllib.request import Request,urlopen
import boto3
from io import StringIO
from botocore.client import Config
import pandas as pd
import requests

In [4]:

url = "https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/npm-covid-data/"

headers = {
	"X-RapidAPI-Host": "vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com",
	"X-RapidAPI-Key": ""
}

response = requests.request("GET", url, headers=headers)
mydata = response.json()
df_json = pd.DataFrame(mydata)
df_json.drop(['TwoLetterSymbol', 'ThreeLetterSymbol'], axis=1, inplace=True)
df_json[['TotalRecovered',"TotalTests",'Population']] = df_json[['TotalRecovered',"TotalTests",'Population']].astype(int)
df_json

,id,rank,Country,Continent,Infection_Risk,Case_Fatality_Rate,Test_Percentage,Recovery_Proporation,TotalCases,NewCases,...,ActiveCases,TotalTests,Population,one_Caseevery_X_ppl,one_Deathevery_X_ppl,one_Testevery_X_ppl,Deaths_1M_pop,Serious_Critical,Tests_1M_Pop,TotCases_1M_Pop
0,40f44943-8413-4a31-a4df-deee8111f85f,0,World,All,0.00,1.28,0.00,86.35,478763632,966487,...,59223116,0,0,0,0,0,787.2,59818,0,61421.0
1,63492a0f-56d7-4c00-9ac1-d64fd5414029,0,Total:,All,0.00,1.28,0.00,86.35,478763632,966487,...,59223116,0,0,0,0,0,787.2,59818,0,61420.9
2,be02608d-a52f-4586-ae9b-220dee7daaf1,1,USA,North America,24.40,1.23,292.17,78.25,81565957,0,...,16739304,976855043,334347663,4,334,0,2998.0,2663,2921675,243956.0
3,f6ecf8d7-5867-42dc-9290-24fda4cb14f0,2,India,Asia,3.07,1.20,55.98,98.75,43016372,0,...,21500,785644225,1403383978,33,2716,2,368.0,8944,559821,30652.0
4,338a3103-483a-4292-9559-1aac2ed47a90,3,Brazil,South America,13.83,2.21,29.64,95.43,29767681,0,...,701857,63776166,215163281,7,327,3,3060.0,8318,296408,138349.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,f4fd07f5-e786-4153-bafe-7b35194a7eef,220,Vatican City,Europe,3.61,0.00,0.00,96.55,29,0,...,1,0,804,28,0,0,0.0,0,0,36070.0
218,98a06a3a-311a-445f-9caf-3b967e1ffef5,221,Western Sahara,Africa,0.00,10.00,0.00,80.00,10,0,...,1,0,622628,62263,622628,0,2.0,0,0,16.0
219,fa63e305-e10f-4b5d-a400-2edd6dcab0f4,222,MS Zaandam,,0.00,22.22,0.00,77.78,9,0,...,0,0,0,0,0,0,0.0,0,0,0.0
220,4088c3ae-7003-40cf-971a-8db0325a24a0,223,Marshall Islands,Australia/Oceania,0.01,0.00,0.00,100.00,7,0,...,0,0,59878,8554,0,0,0.0,0,0,117.0
221,eb9b3fbc-6738-4a35-a943-42a0e05ea149,227,China,Asia,0.01,3.30,11.12,77.58,140651,1366,...,26894,160000000,1439323776,10233,310333,9,3.0,50,111163,98.0